replicaCount:
  front: 1
  back: 1

image:
  front:
    repository: rdegtyarev/vue-project
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  back:
    repository: rdegtyarev/netology-hw-13.01-back
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

appPort:
  front: 80
  back: 9000
